Traceback (most recent call last):
  File "proc_anotated_file.py", line 13, in <module>
    f_in = ano_file.write_to_json()
  File "/home/admin/text_processing/preprocess/proc_anotated_excel.py", line 20, in write_to_json
    df_tmp = df_tmp[['id',	'source', 'date', 'title', 'content', 'label']]
  File "/home/admin/venv-textproc/lib/python3.7/site-packages/pandas/core/frame.py", line 2806, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/admin/venv-textproc/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/home/admin/venv-textproc/lib/python3.7/site-packages/pandas/core/indexing.py", line 1646, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['label'] not in index"
Traceback (most recent call last):
  File "proc_anotated_file.py", line 13, in <module>
    f_in = ano_file.write_to_json()
  File "/home/admin/text_processing/preprocess/proc_anotated_excel.py", line 20, in write_to_json
    df_tmp = df_tmp[['id',	'source', 'date', 'title', 'content', 'label']]
  File "/home/admin/venv-textproc/lib/python3.7/site-packages/pandas/core/frame.py", line 2806, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/admin/venv-textproc/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/home/admin/venv-textproc/lib/python3.7/site-packages/pandas/core/indexing.py", line 1646, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['label'] not in index"
